import { readFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

async function readRoot(file: string): Promise<string> {
  return readFile(path.join(process.cwd(), file), "utf8");
}

const generatedExampleReadmes = [
  "examples/01-read-only-report/README.md",
  "examples/02-clarification/README.md",
  "examples/03-email-drafts/README.md",
  "examples/04-confirmed-send/README.md",
  "examples/05-policy-denial/README.md",
  "examples/06-log-analysis/README.md",
  "examples-chat/01-short-agreement/README.md",
  "examples-chat/02-long-negotiation-agreement/README.md",
  "examples-chat/03-short-conversation-cancelled/README.md",
  "examples-chat/04-long-negotiation-cancelled/README.md",
  "examples-recruitment/01-multi-candidate/README.md",
  "examples-recruitment/01-multi-candidate/001-anna-nowak-md2pdf/README.md",
  "examples-recruitment/01-multi-candidate/002-anna-nowak-pdf2md/README.md",
  "examples-recruitment/01-multi-candidate/001-anna-nowak/README.md",
  "examples-recruitment/01-multi-candidate/002-bartek-lis/README.md",
  "examples-recruitment/02-single-candidate-agreement/README.md",
  "examples-recruitment/02-single-candidate-agreement/001-ewa-zielinska-md2pdf/README.md",
  "examples-recruitment/02-single-candidate-agreement/001-ewa-zielinska/README.md",
  "examples-recruitment/03-negotiated-two-candidates/README.md",
  "examples-recruitment/03-negotiated-two-candidates/001-ola-maj-md2pdf/README.md",
  "examples-recruitment/03-negotiated-two-candidates/002-jan-kot-pdf2md/README.md",
  "examples-recruitment/03-negotiated-two-candidates/001-ola-maj/README.md",
  "examples-recruitment/03-negotiated-two-candidates/002-jan-kot/README.md",
  "examples-recruitment/04-ocr-candidate-cancelled/README.md",
  "examples-recruitment/04-ocr-candidate-cancelled/001-kasia-wrona-pdf2md/README.md",
  "examples-recruitment/04-ocr-candidate-cancelled/001-kasia-wrona/README.md"
];

describe("generated documentation", () => {
  it("keeps README include menu, docs index, script, and Makefile wired together", async () => {
    const readme = await readRoot("README.md");
    const docsIndex = await readRoot("docs/documentation-index.md");
    const makefile = await readRoot("Makefile");
    const readmeScript = await readRoot("script/readme.sh");
    const projectSh = await readRoot("project.sh");
    const projectBat = await readRoot("project.bat");
    const officeReadme = await readRoot("examples/01-read-only-report/README.md");
    const chatReadme = await readRoot("examples-chat/01-short-agreement/README.md");
    const recruitmentReadme = await readRoot("examples-recruitment/01-multi-candidate/README.md");
    const documentProcessReadme = await readRoot(
      "examples-recruitment/01-multi-candidate/001-anna-nowak-md2pdf/README.md"
    );
    const candidateReadme = await readRoot(
      "examples-recruitment/01-multi-candidate/001-anna-nowak/README.md"
    );

    expect(readme).toContain("<!-- generated-docs:start -->");
    expect(readme).toContain("Generated by `script/readme.sh`");
    expect(readme).toContain("### Document Menu");
    expect(readme).toContain("### Example Menu");
    expect(readme).toContain("docs/documentation-index.md");
    expect(readme).toContain("examples-recruitment/04-ocr-candidate-cancelled/README.md");

    expect(docsIndex).toContain("## Documents");
    expect(docsIndex).toContain("## Example Scenarios");
    expect(docsIndex).toContain("codex-sandbox-vitest.md");
    expect(docsIndex).toContain("package-boundary-audit.md");
    expect(docsIndex).toContain("04-ocr-candidate-cancelled");

    expect(makefile).toContain("makedocs:");
    expect(makefile).toContain("docs-check:");
    expect(readmeScript).toContain("corepack pnpm run docs:generate");
    expect(projectSh).toContain("makedocs)");
    expect(projectBat).toContain(":makedocs");
    expect(officeReadme).toContain("Generated by `script/readme.sh`");
    expect(officeReadme).toContain("actual.dsl.hcl");
    expect(chatReadme).toContain("Final contract/PDF/approvals");
    expect(recruitmentReadme).toContain("## Document Processes");
    expect(recruitmentReadme).toContain("001-anna-nowak-md2pdf");
    expect(recruitmentReadme).toContain("002-anna-nowak-pdf2md");
    expect(recruitmentReadme).toContain("## Candidates");
    expect(documentProcessReadme).toContain("one runnable document process fixture");
    expect(candidateReadme).toContain("## Document Processes");
  });

  it("generates one README for every example, document process, and recruitment candidate folder", async () => {
    for (const file of generatedExampleReadmes) {
      const readme = await readRoot(file);
      expect(readme).toContain("Generated by `script/readme.sh`");
      expect(readme).toContain("## Summary");
    }
  });
});
