#!/usr/bin/env node
import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { buildExamplesArtifactsIndex } from "./examples-index.js";

type JsonObject = Record<string, unknown>;

interface DocEntry {
  file: string;
  title: string;
  description: string;
}

interface ExampleEntry {
  group: string;
  groupDir: string;
  command: string;
  id: string;
  title: string;
  dir: string;
  manifestFile: string;
  expected: string[];
  manifest: JsonObject;
}

interface CandidateEntry {
  id: string;
  title: string;
  dir: string;
  manifest: JsonObject;
}

interface DocumentProcessEntry {
  id: string;
  process: string;
  dir: string;
  test: JsonObject;
}

const README_START = "<!-- generated-docs:start -->";
const README_END = "<!-- generated-docs:end -->";

const ROOT_DOC_FILES = [
  "README.md",
  "TODO.md",
  "ROADMAP.md",
  "HANDOFF.md",
  "VERSION",
  "CHANGELOG.md",
  "CONTRIBUTING.md",
  "POLICY.md"
];

const EXAMPLE_GROUPS = [
  { label: "Office examples", dir: "examples", command: ".\\project.bat examples" },
  { label: "Chat examples", dir: "examples-chat", command: ".\\project.bat examples-chat" },
  {
    label: "Recruitment examples",
    dir: "examples-recruitment",
    command: ".\\project.bat examples-recruitment"
  }
];

export async function generateReadmeDocs(repoRoot = process.cwd()): Promise<void> {
  await writeFile(
    path.join(repoRoot, "docs", "examples-artifacts-index.md"),
    await buildExamplesArtifactsIndex(repoRoot),
    "utf8"
  );

  const examples = await readExamples(repoRoot);
  await writeExampleReadmes(repoRoot, examples);

  const docs = await readDocs(repoRoot);
  await writeFile(
    path.join(repoRoot, "docs", "documentation-index.md"),
    renderDocumentationIndex(docs, examples),
    "utf8"
  );
  await updateReadme(repoRoot, docs, examples);
}

async function readDocs(repoRoot: string): Promise<DocEntry[]> {
  const docs: DocEntry[] = [];
  const rootDocs = [...ROOT_DOC_FILES, ...(await markdownFilesIn(repoRoot, ""))];
  const docsDirDocs = (await markdownFilesIn(repoRoot, "docs")).map((file) => `docs/${file}`);
  for (const file of unique([...rootDocs, ...docsDirDocs])) {
    const fullPath = path.join(repoRoot, file);
    if (!(await exists(fullPath))) continue;
    const content = await readFile(fullPath, "utf8");
    docs.push({ file, ...describeMarkdown(content, file) });
  }
  return docs.sort((a, b) => docSortKey(a.file).localeCompare(docSortKey(b.file)));
}

async function readExamples(repoRoot: string): Promise<ExampleEntry[]> {
  const examples: ExampleEntry[] = [];
  for (const group of EXAMPLE_GROUPS) {
    const root = path.join(repoRoot, group.dir);
    for (const dir of await listChildDirs(root)) {
      const manifestPath = path.join(dir, "scenario.json");
      if (!(await exists(manifestPath))) continue;
      const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as JsonObject;
      examples.push({
        group: group.label,
        groupDir: group.dir,
        command: group.command,
        id: String(manifest.id ?? path.basename(dir)),
        title: String(manifest.title ?? path.basename(dir)),
        dir,
        manifestFile: path.relative(repoRoot, manifestPath).replace(/\\/g, "/"),
        expected: Object.values(objectValue(manifest.expected)).map(String).sort(),
        manifest
      });
    }
  }
  return examples.sort((a, b) => `${a.group}:${a.id}`.localeCompare(`${b.group}:${b.id}`));
}

async function writeExampleReadmes(repoRoot: string, examples: ExampleEntry[]): Promise<void> {
  for (const example of examples) {
    await writeFile(
      path.join(example.dir, "README.md"),
      await renderExampleReadme(repoRoot, example),
      "utf8"
    );
    if (example.groupDir === "examples-recruitment") {
      for (const process of await readScenarioDocumentProcesses(example.dir)) {
        await writeFile(
          path.join(process.dir, "README.md"),
          await renderDocumentProcessReadme(repoRoot, example, process),
          "utf8"
        );
      }
      for (const candidate of await readCandidates(example.dir)) {
        await writeFile(
          path.join(candidate.dir, "README.md"),
          await renderCandidateReadme(repoRoot, example, candidate),
          "utf8"
        );
      }
    }
  }
}

async function renderExampleReadme(repoRoot: string, example: ExampleEntry): Promise<string> {
  const lines: string[] = [];
  lines.push(`# ${example.id}: ${example.title}`, "");
  lines.push("Generated by `script/readme.sh`. Do not edit this file by hand.", "");
  lines.push("## Summary", "");
  lines.push(`- Group: ${example.group}`);
  lines.push(`- Runner: \`${example.command}\``);
  lines.push(
    `- Manifest: ${localLink(example.dir, path.join(example.dir, "scenario.json"), "scenario.json")}`
  );
  lines.push(
    `- Expected fixtures: ${localFiles(example.dir, await expectedFilesForDir(example.dir)) || "none"}`
  );
  lines.push(`- Output location: ${outputLocations(example.dir, example.groupDir)}`);
  const result = await expectedResult(example);
  if (result) lines.push(`- Expected result: ${result}`);
  lines.push("", "## Inputs", "");
  lines.push(
    localFiles(example.dir, await inputFiles(example)) ||
      "No direct input files declared at scenario root."
  );
  lines.push("", "## Generated Artifacts", "");
  lines.push(generatedNotes(example.groupDir));
  if (example.groupDir === "examples-recruitment") {
    const processes = await readScenarioDocumentProcesses(example.dir);
    lines.push("", "## Document Processes", "");
    for (const process of processes) {
      lines.push(
        `- ${localLink(example.dir, path.join(process.dir, "README.md"), `${process.id}: ${process.process}`)}`
      );
    }
    if (!processes.length) lines.push("No scenario-level document processes declared.");

    const candidates = await readCandidates(example.dir);
    lines.push("", "## Candidates", "");
    for (const candidate of candidates) {
      lines.push(
        `- ${localLink(example.dir, path.join(candidate.dir, "README.md"), `${candidate.id}: ${candidate.title}`)}`
      );
    }
  }
  lines.push("", "## Related Indexes", "");
  lines.push(
    `- ${localLink(example.dir, path.join(repoRoot, "docs", "examples-artifacts-index.md"), "examples artifacts index")}`
  );
  lines.push(
    `- ${localLink(example.dir, path.join(repoRoot, "docs", "documentation-index.md"), "documentation index")}`
  );
  lines.push("");
  return lines.join("\n");
}

async function renderCandidateReadme(
  repoRoot: string,
  example: ExampleEntry,
  candidate: CandidateEntry
): Promise<string> {
  const lines: string[] = [];
  lines.push(`# ${candidate.id}: ${candidate.title}`, "");
  lines.push("Generated by `script/readme.sh`. Do not edit this file by hand.", "");
  lines.push("## Summary", "");
  lines.push(
    `- Parent example: ${localLink(candidate.dir, path.join(example.dir, "README.md"), example.id)}`
  );
  lines.push(`- Runner: \`${example.command}\``);
  lines.push(
    `- Manifest: ${localLink(candidate.dir, path.join(candidate.dir, "scenario.json"), "scenario.json")}`
  );
  lines.push(
    `- Chat: ${localMaybe(candidate.dir, path.join(candidate.dir, "chat.txt"), "chat.txt")}`
  );
  lines.push(
    `- Expected fixtures: ${localFiles(candidate.dir, await expectedFilesForDir(candidate.dir)) || "none"}`
  );
  lines.push(
    `- Output location: ${localLink(candidate.dir, path.join(candidate.dir, "out"), "out/")}`
  );
  const result = await expectedCandidateResult(candidate);
  if (result) lines.push(`- Expected result: ${result}`);
  lines.push("", "## Inputs", "");
  lines.push(
    localFiles(candidate.dir, await filesInDir(path.join(candidate.dir, "in"))) ||
      "No candidate input files found."
  );
  lines.push("", "## Document Processes", "");
  lines.push(
    "Document-process fixtures are scenario-level folders next to candidate folders, with one `test.json`, one `in/` side, and one `out/` side per process."
  );
  lines.push("", "## Generated Artifacts", "");
  lines.push(
    "Candidate final/proposal/status artifacts are written to `out/` by the recruitment runner. Accepted candidates may receive `contract.dsl.txt`; rejected candidates must not rely on a final contract."
  );
  lines.push("");
  return lines.join("\n");
}
async function renderDocumentProcessReadme(
  repoRoot: string,
  example: ExampleEntry,
  process: DocumentProcessEntry
): Promise<string> {
  const lines: string[] = [];
  lines.push(`# ${process.id}: ${process.process}`, "");
  lines.push("Generated by `script/readme.sh`. Do not edit this file by hand.", "");
  lines.push("## Summary", "");
  lines.push(
    `- Parent example: ${localLink(process.dir, path.join(example.dir, "README.md"), example.id)}`
  );
  lines.push(`- Runner: \`${example.command}\``);
  lines.push(`- Process: \`${process.process}\``);
  lines.push(`- Test: ${localLink(process.dir, path.join(process.dir, "test.json"), "test.json")}`);
  lines.push(
    `- Input: ${localFiles(process.dir, await filesInDir(path.join(process.dir, "in"))) || "none"}`
  );
  lines.push(
    `- Output: ${localFiles(process.dir, await filesInDir(path.join(process.dir, "out"))) || "none"}`
  );
  lines.push("", "## Contract", "");
  lines.push(
    "This folder is one runnable document process fixture: one `test.json`, one `in/` side, and one `out/` side. The recruitment runner validates the process result against `test.json`."
  );
  lines.push("", "## Related Indexes", "");
  lines.push(
    `- ${localLink(process.dir, path.join(repoRoot, "docs", "examples-artifacts-index.md"), "examples artifacts index")}`
  );
  lines.push("");
  return lines.join("\n");
}

function renderDocumentationIndex(docs: DocEntry[], examples: ExampleEntry[]): string {
  const lines: string[] = [];
  lines.push("# Documentation Index", "");
  lines.push("Generated by `script/readme.sh`. Do not edit this file by hand.", "");
  lines.push("## Documents", "");
  lines.push("| Document | What It Contains |");
  lines.push("| --- | --- |");
  for (const doc of docs) {
    lines.push(`| ${docsIndexLink(doc.file, doc.title)} | ${escapeTable(doc.description)} |`);
  }
  lines.push("", "## Example Scenarios", "");
  lines.push("| Group | Scenario | Expected Fixtures |");
  lines.push("| --- | --- | --- |");
  for (const example of examples) {
    const expected = example.expected.length
      ? example.expected.map((item) => `\`${item}\``).join(", ")
      : "none";
    const readmeFile = path
      .join(path.dirname(example.manifestFile), "README.md")
      .replace(/\\/g, "/");
    lines.push(
      `| ${example.group} | ${docsIndexLink(readmeFile, `${example.id}: ${example.title}`)} | ${expected} |`
    );
  }
  lines.push("", "## Commands", "");
  lines.push("| Command | Purpose |");
  lines.push("| --- | --- |");
  lines.push(
    "| `make makedocs` | Regenerate README include menu, documentation indexes, and per-example README files. |"
  );
  lines.push("| `make docs-check` | Regenerate documentation and fail if tracked files changed. |");
  lines.push("| `make verify` | Run the full repository verification through `project.sh`. |");
  for (const group of EXAMPLE_GROUPS)
    lines.push(`| \`${group.command}\` | Run ${group.label.toLowerCase()}. |`);
  lines.push("");
  return `${lines.join("\n").trimEnd()}\n`;
}

async function updateReadme(
  repoRoot: string,
  docs: DocEntry[],
  examples: ExampleEntry[]
): Promise<void> {
  const readmePath = path.join(repoRoot, "README.md");
  const readme = await readFile(readmePath, "utf8");
  const block = renderReadmeBlock(docs, examples);
  const replacement = `${README_START}\n${block.trimEnd()}\n${README_END}`;
  let next: string;
  if (readme.includes(README_START) && readme.includes(README_END)) {
    const pattern = new RegExp(
      `${escapeRegExp(README_START)}[\\s\\S]*?${escapeRegExp(README_END)}`
    );
    next = readme.replace(pattern, replacement);
  } else {
    const heading = "## Documentation";
    const index = readme.indexOf(heading);
    if (index === -1) throw new Error("README.md must contain a Documentation section");
    const before = readme.slice(0, index + heading.length);
    next = `${before}\n\n${replacement}\n`;
  }
  await writeFile(readmePath, `${next.trimEnd()}\n`, "utf8");
}

function renderReadmeBlock(docs: DocEntry[], examples: ExampleEntry[]): string {
  const lines: string[] = [];
  lines.push("Generated by `script/readme.sh`. Do not edit this block by hand.", "");
  lines.push("### Document Menu", "");
  for (const doc of docs.filter((doc) => doc.file !== "README.md")) {
    lines.push(`- ${relativeLink(doc.file, doc.title)} - ${doc.description}`);
  }
  lines.push("", "### Example Menu", "");
  for (const group of EXAMPLE_GROUPS) {
    lines.push(`- ${group.label} - run with \`${group.command}\``);
    for (const example of examples.filter((example) => example.group === group.label)) {
      const readmeFile = path
        .join(path.dirname(example.manifestFile), "README.md")
        .replace(/\\/g, "/");
      lines.push(`  - ${relativeLink(readmeFile, `${example.id}: ${example.title}`)}`);
    }
  }
  lines.push("", "Full generated indexes:");
  lines.push("- [docs/documentation-index.md](docs/documentation-index.md)");
  lines.push("- [docs/examples-artifacts-index.md](docs/examples-artifacts-index.md)");
  lines.push("");
  return lines.join("\n");
}

async function readCandidates(exampleDir: string): Promise<CandidateEntry[]> {
  const candidates: CandidateEntry[] = [];
  for (const dir of await listChildDirs(exampleDir)) {
    const manifestPath = path.join(dir, "scenario.json");
    if (!(await exists(manifestPath))) continue;
    const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as JsonObject;
    candidates.push({
      id: String(manifest.id ?? path.basename(dir)),
      title: String(manifest.title ?? path.basename(dir)),
      dir,
      manifest
    });
  }
  return candidates.sort((a, b) => a.id.localeCompare(b.id));
}

async function readScenarioDocumentProcesses(exampleDir: string): Promise<DocumentProcessEntry[]> {
  const processes: DocumentProcessEntry[] = [];
  for (const dir of await listChildDirs(exampleDir)) {
    const testPath = path.join(dir, "test.json");
    if (!(await exists(testPath))) continue;
    const test = JSON.parse(await readFile(testPath, "utf8")) as JsonObject;
    processes.push({
      id: String(test.id ?? path.basename(dir)),
      process: String(test.process ?? path.basename(dir)),
      dir,
      test
    });
  }
  return processes.sort((a, b) => a.id.localeCompare(b.id));
}
async function inputFiles(example: ExampleEntry): Promise<string[]> {
  const input = objectValue(example.manifest.input);
  const files: string[] = [];
  for (const value of Object.values(input)) {
    if (typeof value === "string") files.push(path.join(example.dir, value));
    if (Array.isArray(value))
      for (const item of value)
        if (typeof item === "string") files.push(path.join(example.dir, item));
  }
  if (example.groupDir === "examples-chat") files.push(path.join(example.dir, "chat.txt"));
  return existingOnly(unique(files));
}

async function expectedResult(example: ExampleEntry): Promise<string | undefined> {
  const summary = await readOptionalJson(path.join(example.dir, "expected", "summary.json"));
  if (!summary) return undefined;
  if (example.groupDir === "examples-chat") {
    return `${String(summary.outcome ?? "UNKNOWN")}; final created: ${String(summary.finalCreated ?? summary.final_created ?? "unknown")}`;
  }
  if (example.groupDir === "examples-recruitment") {
    const accepted = Array.isArray(summary.accepted) ? summary.accepted.length : 0;
    const rejected = Array.isArray(summary.rejected) ? summary.rejected.length : 0;
    return `accepted: ${accepted}; rejected: ${rejected}`;
  }
  return undefined;
}

async function expectedCandidateResult(candidate: CandidateEntry): Promise<string | undefined> {
  const summary = await readOptionalJson(path.join(candidate.dir, "expected", "summary.json"));
  if (!summary) return undefined;
  const outcome = summary.outcome ?? summary.chatOutcome ?? "UNKNOWN";
  const finalCreated = summary.finalCreated ?? summary.final_created ?? "unknown";
  return `${String(outcome)}; final created: ${String(finalCreated)}`;
}

function generatedNotes(groupDir: string): string {
  if (groupDir === "examples") {
    return "The office runner writes `actual.dsl.hcl`, validation, questions, plan, and verifier artifacts under `generated/`.";
  }
  if (groupDir === "examples-chat") {
    return "The chat runner writes line-by-line diff, party contract, merged contract, status, summary, and finalization artifacts under `generated/`. Final contract/PDF/approvals only appear after both parties approve the same current hash.";
  }
  return "The recruitment runner writes scenario summary artifacts under `generated/` and candidate-local proposal/status/final contract artifacts under each candidate `out/` folder.";
}

function outputLocations(baseDir: string, groupDir: string): string {
  const locations = [localLink(baseDir, path.join(baseDir, "generated"), "generated/")];
  if (groupDir !== "examples-chat")
    locations.push(localLink(baseDir, path.join(baseDir, "out"), "out/"));
  return locations.join(", ");
}

async function expectedFilesForDir(dir: string): Promise<string[]> {
  return filesInDir(path.join(dir, "expected"));
}

async function readOptionalJson(file: string): Promise<JsonObject | undefined> {
  if (!(await exists(file))) return undefined;
  return JSON.parse(await readFile(file, "utf8")) as JsonObject;
}

async function markdownFilesIn(repoRoot: string, dir: string): Promise<string[]> {
  const fullDir = path.join(repoRoot, dir);
  if (!(await exists(fullDir))) return [];
  const entries = await readdir(fullDir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

function docSortKey(file: string): string {
  const rootIndex = ROOT_DOC_FILES.indexOf(file);
  if (rootIndex >= 0) return `0:${rootIndex.toString().padStart(3, "0")}:${file}`;
  return `1:${file}`;
}

function describeMarkdown(content: string, fallback: string): Omit<DocEntry, "file"> {
  const lines = content.split(/\r?\n/);
  const heading = lines.find((line) => /^#\s+\S/.test(line));
  const title = heading ? heading.replace(/^#\s+/, "").trim() : path.basename(fallback);
  const purpose = content.match(/PURPOSE\s+"([^"]+)"/i)?.[1];
  const description = firstMarkdownParagraph(lines) ?? purpose;
  return { title, description: compactDescription(description ?? "Project document.") };
}

function compactDescription(value: string): string {
  const compact = value.replace(/\s+/g, " ").trim();
  if (compact.length <= 220) return compact;
  return `${compact.slice(0, 217).trimEnd()}...`;
}

function firstMarkdownParagraph(lines: string[]): string | undefined {
  const paragraph: string[] = [];
  let inFence = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("```")) {
      inFence = !inFence;
      continue;
    }
    if (inFence || !trimmed || trimmed.startsWith("#") || trimmed.startsWith("<!--")) {
      if (paragraph.length) break;
      continue;
    }
    if (trimmed.startsWith("Date:")) continue;
    paragraph.push(trimmed.replace(/^[->*\s]+/, "").trim());
  }
  const joined = paragraph.join(" ").trim();
  return joined && /[A-Za-z0-9]/.test(joined) ? joined : undefined;
}

async function listChildDirs(dir: string): Promise<string[]> {
  if (!(await exists(dir))) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(dir, entry.name))
    .sort((a, b) => a.localeCompare(b));
}

async function filesInDir(dir: string): Promise<string[]> {
  if (!(await exists(dir))) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => path.join(dir, entry.name))
    .sort((a, b) => a.localeCompare(b));
}

async function existingOnly(files: string[]): Promise<string[]> {
  const existing: string[] = [];
  for (const file of files) if (await exists(file)) existing.push(file);
  return existing;
}

async function exists(file: string): Promise<boolean> {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

function objectValue(value: unknown): JsonObject {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as JsonObject) : {};
}

function docsIndexLink(file: string, label: string): string {
  const normalized = file.replace(/\\/g, "/");
  const href = normalized.startsWith("docs/")
    ? normalized.slice("docs/".length)
    : `../${normalized}`;
  return `[${escapeTable(label)}](${href})`;
}

function relativeLink(file: string, label: string): string {
  return `[${escapeTable(label)}](${file.replace(/\\/g, "/")})`;
}

function localFiles(baseDir: string, files: string[]): string {
  return files.map((file) => localLink(baseDir, file, path.basename(file))).join(", ");
}

function localMaybe(baseDir: string, file: string, label: string): string {
  return `[${escapeTable(label)}](${path.relative(baseDir, file).replace(/\\/g, "/")})`;
}

function localLink(baseDir: string, file: string, label: string): string {
  return `[${escapeTable(label)}](${path.relative(baseDir, file).replace(/\\/g, "/")})`;
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

async function main(): Promise<void> {
  await generateReadmeDocs(process.cwd());
  console.log(
    "documentation generated: README.md, docs/documentation-index.md, docs/examples-artifacts-index.md, example README.md files"
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
